/*
 * Copyright (c) 2007 Intel Corporation. All Rights Reserved.
 * Copyright (c) Imagination Technologies Limited, UK  
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sub license, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 * 
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial portions
 * of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
 * IN NO EVENT SHALL PRECISION INSIGHT AND/OR ITS SUPPLIERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************

 @File         dxva_cmdseq_msg.h

 @Title        Debug driver

 @Platform     </b>\n

 @Description  </b>\n This file contains the DXVA_CMDSEQ_MSG_H Definitions.

******************************************************************************/
#if !defined (__DXVA_CMDSEQ_MSG_H__)
#define __DXVA_CMDSEQ_MSG_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Deblock parameters */
typedef struct {
	uint32_t handle;	/* struct ttm_buffer_object * of REGIO */
	uint32_t buffer_size;
	uint32_t ctxid;

	uint32_t *pPicparams; 
	void	 *regio_kmap;	/* virtual of regio */
	uint32_t pad[3];
} DEBLOCKPARAMS;


#define FW_DXVA_RENDER_SIZE		(32)

// FW_DXVA_RENDER     MSG_SIZE
#define FW_DXVA_RENDER_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_RENDER_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_RENDER_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_RENDER_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_RENDER_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_RENDER_MSG_SIZE_SHIFT		(0)

// FW_DXVA_RENDER     ID
#define FW_DXVA_RENDER_ID_ALIGNMENT		(1)
#define FW_DXVA_RENDER_ID_TYPE		IMG_UINT8
#define FW_DXVA_RENDER_ID_MASK		(0xFF)
#define FW_DXVA_RENDER_ID_LSBMASK		(0xFF)
#define FW_DXVA_RENDER_ID_OFFSET		(0x0001)
#define FW_DXVA_RENDER_ID_SHIFT		(0)

// FW_DXVA_RENDER     BUFFER_SIZE
#define FW_DXVA_RENDER_BUFFER_SIZE_ALIGNMENT		(2)
#define FW_DXVA_RENDER_BUFFER_SIZE_TYPE		IMG_UINT16
#define FW_DXVA_RENDER_BUFFER_SIZE_MASK		(0x0FFF)
#define FW_DXVA_RENDER_BUFFER_SIZE_LSBMASK		(0x0FFF)
#define FW_DXVA_RENDER_BUFFER_SIZE_OFFSET		(0x0002)
#define FW_DXVA_RENDER_BUFFER_SIZE_SHIFT		(0)

// FW_DXVA_RENDER     MMUPTD
#define FW_DXVA_RENDER_MMUPTD_ALIGNMENT		(4)
#define FW_DXVA_RENDER_MMUPTD_TYPE		IMG_UINT32
#define FW_DXVA_RENDER_MMUPTD_MASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_MMUPTD_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_MMUPTD_OFFSET		(0x0004)
#define FW_DXVA_RENDER_MMUPTD_SHIFT		(0)

// FW_DXVA_RENDER     LLDMA_ADDRESS
#define FW_DXVA_RENDER_LLDMA_ADDRESS_ALIGNMENT		(4)
#define FW_DXVA_RENDER_LLDMA_ADDRESS_TYPE		IMG_UINT32
#define FW_DXVA_RENDER_LLDMA_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_LLDMA_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_LLDMA_ADDRESS_OFFSET		(0x0008)
#define FW_DXVA_RENDER_LLDMA_ADDRESS_SHIFT		(0)

// FW_DXVA_RENDER     CONTEXT
#define FW_DXVA_RENDER_CONTEXT_ALIGNMENT		(4)
#define FW_DXVA_RENDER_CONTEXT_TYPE		IMG_UINT32
#define FW_DXVA_RENDER_CONTEXT_MASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_CONTEXT_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_CONTEXT_OFFSET		(0x000C)
#define FW_DXVA_RENDER_CONTEXT_SHIFT		(0)

// FW_DXVA_RENDER     FENCE_VALUE
#define FW_DXVA_RENDER_FENCE_VALUE_ALIGNMENT		(4)
#define FW_DXVA_RENDER_FENCE_VALUE_TYPE		IMG_UINT32
#define FW_DXVA_RENDER_FENCE_VALUE_MASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_FENCE_VALUE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_FENCE_VALUE_OFFSET		(0x0010)
#define FW_DXVA_RENDER_FENCE_VALUE_SHIFT		(0)

// FW_DXVA_RENDER     OPERATING_MODE
#define FW_DXVA_RENDER_OPERATING_MODE_ALIGNMENT		(4)
#define FW_DXVA_RENDER_OPERATING_MODE_TYPE		IMG_UINT32
#define FW_DXVA_RENDER_OPERATING_MODE_MASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_OPERATING_MODE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_OPERATING_MODE_OFFSET		(0x0014)
#define FW_DXVA_RENDER_OPERATING_MODE_SHIFT		(0)

// FW_DXVA_RENDER     FIRST_MB_IN_SLICE
#define FW_DXVA_RENDER_FIRST_MB_IN_SLICE_ALIGNMENT		(2)
#define FW_DXVA_RENDER_FIRST_MB_IN_SLICE_TYPE		IMG_UINT16
#define FW_DXVA_RENDER_FIRST_MB_IN_SLICE_MASK		(0xFFFF)
#define FW_DXVA_RENDER_FIRST_MB_IN_SLICE_LSBMASK		(0xFFFF)
#define FW_DXVA_RENDER_FIRST_MB_IN_SLICE_OFFSET		(0x0018)
#define FW_DXVA_RENDER_FIRST_MB_IN_SLICE_SHIFT		(0)

// FW_DXVA_RENDER     LAST_MB_IN_FRAME
#define FW_DXVA_RENDER_LAST_MB_IN_FRAME_ALIGNMENT		(2)
#define FW_DXVA_RENDER_LAST_MB_IN_FRAME_TYPE		IMG_UINT16
#define FW_DXVA_RENDER_LAST_MB_IN_FRAME_MASK		(0xFFFF)
#define FW_DXVA_RENDER_LAST_MB_IN_FRAME_LSBMASK		(0xFFFF)
#define FW_DXVA_RENDER_LAST_MB_IN_FRAME_OFFSET		(0x001A)
#define FW_DXVA_RENDER_LAST_MB_IN_FRAME_SHIFT		(0)

// FW_DXVA_RENDER     FLAGS
#define FW_DXVA_RENDER_FLAGS_ALIGNMENT		(4)
#define FW_DXVA_RENDER_FLAGS_TYPE		IMG_UINT32
#define FW_DXVA_RENDER_FLAGS_MASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_FLAGS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_RENDER_FLAGS_OFFSET		(0x001C)
#define FW_DXVA_RENDER_FLAGS_SHIFT		(0)

#define FW_DXVA_DEBLOCK_SIZE		(16 + 32) /* 32 bytes for DEBLOCKPARAMS */

// FW_DXVA_DEBLOCK     MSG_SIZE
#define FW_DXVA_DEBLOCK_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_DEBLOCK_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_DEBLOCK_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_DEBLOCK_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_DEBLOCK_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_DEBLOCK_MSG_SIZE_SHIFT		(0)

// FW_DXVA_DEBLOCK     ID
#define FW_DXVA_DEBLOCK_ID_ALIGNMENT		(1)
#define FW_DXVA_DEBLOCK_ID_TYPE		IMG_UINT8
#define FW_DXVA_DEBLOCK_ID_MASK		(0xFF)
#define FW_DXVA_DEBLOCK_ID_LSBMASK		(0xFF)
#define FW_DXVA_DEBLOCK_ID_OFFSET		(0x0001)
#define FW_DXVA_DEBLOCK_ID_SHIFT		(0)

// FW_DXVA_DEBLOCK     FLAGS
#define FW_DXVA_DEBLOCK_FLAGS_ALIGNMENT		(2)
#define FW_DXVA_DEBLOCK_FLAGS_TYPE		IMG_UINT16
#define FW_DXVA_DEBLOCK_FLAGS_MASK		(0xFFFF)
#define FW_DXVA_DEBLOCK_FLAGS_LSBMASK		(0xFFFF)
#define FW_DXVA_DEBLOCK_FLAGS_OFFSET		(0x0002)
#define FW_DXVA_DEBLOCK_FLAGS_SHIFT		(0)

// FW_DXVA_DEBLOCK     CONTEXT
#define FW_DXVA_DEBLOCK_CONTEXT_ALIGNMENT		(4)
#define FW_DXVA_DEBLOCK_CONTEXT_TYPE		IMG_UINT32
#define FW_DXVA_DEBLOCK_CONTEXT_MASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_CONTEXT_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_CONTEXT_OFFSET		(0x0004)
#define FW_DXVA_DEBLOCK_CONTEXT_SHIFT		(0)

// FW_DXVA_DEBLOCK     FENCE_VALUE
#define FW_DXVA_DEBLOCK_FENCE_VALUE_ALIGNMENT		(4)
#define FW_DXVA_DEBLOCK_FENCE_VALUE_TYPE		IMG_UINT32
#define FW_DXVA_DEBLOCK_FENCE_VALUE_MASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_FENCE_VALUE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_FENCE_VALUE_OFFSET		(0x0008)
#define FW_DXVA_DEBLOCK_FENCE_VALUE_SHIFT		(0)

// FW_DXVA_DEBLOCK     MMUPTD
#define FW_DXVA_DEBLOCK_MMUPTD_ALIGNMENT		(4)
#define FW_DXVA_DEBLOCK_MMUPTD_TYPE		IMG_UINT32
#define FW_DXVA_DEBLOCK_MMUPTD_MASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_MMUPTD_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_MMUPTD_OFFSET		(0x000C)
#define FW_DXVA_DEBLOCK_MMUPTD_SHIFT		(0)

#define FW_DXVA_OOLD_SIZE		(40)

// FW_DXVA_OOLD     MSG_SIZE
#define FW_DXVA_OOLD_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_OOLD_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_OOLD_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_OOLD_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_OOLD_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_OOLD_MSG_SIZE_SHIFT		(0)

// FW_DXVA_OOLD     ID
#define FW_DXVA_OOLD_ID_ALIGNMENT		(1)
#define FW_DXVA_OOLD_ID_TYPE		IMG_UINT8
#define FW_DXVA_OOLD_ID_MASK		(0xFF)
#define FW_DXVA_OOLD_ID_LSBMASK		(0xFF)
#define FW_DXVA_OOLD_ID_OFFSET		(0x0001)
#define FW_DXVA_OOLD_ID_SHIFT		(0)

// FW_DXVA_OOLD     SLICE_FIELD_TYPE
#define FW_DXVA_OOLD_SLICE_FIELD_TYPE_ALIGNMENT		(1)
#define FW_DXVA_OOLD_SLICE_FIELD_TYPE_TYPE		IMG_UINT8
#define FW_DXVA_OOLD_SLICE_FIELD_TYPE_MASK		(0x03)
#define FW_DXVA_OOLD_SLICE_FIELD_TYPE_LSBMASK		(0x03)
#define FW_DXVA_OOLD_SLICE_FIELD_TYPE_OFFSET		(0x0002)
#define FW_DXVA_OOLD_SLICE_FIELD_TYPE_SHIFT		(0)

// FW_DXVA_OOLD     MMUPTD
#define FW_DXVA_OOLD_MMUPTD_ALIGNMENT		(4)
#define FW_DXVA_OOLD_MMUPTD_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_MMUPTD_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_MMUPTD_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_MMUPTD_OFFSET		(0x0004)
#define FW_DXVA_OOLD_MMUPTD_SHIFT		(0)

// FW_DXVA_OOLD     FENCE_VALUE
#define FW_DXVA_OOLD_FENCE_VALUE_ALIGNMENT		(4)
#define FW_DXVA_OOLD_FENCE_VALUE_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_FENCE_VALUE_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_FENCE_VALUE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_FENCE_VALUE_OFFSET		(0x0008)
#define FW_DXVA_OOLD_FENCE_VALUE_SHIFT		(0)

// FW_DXVA_OOLD     OPERATING_MODE
#define FW_DXVA_OOLD_OPERATING_MODE_ALIGNMENT		(4)
#define FW_DXVA_OOLD_OPERATING_MODE_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_OPERATING_MODE_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_OPERATING_MODE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_OPERATING_MODE_OFFSET		(0x000C)
#define FW_DXVA_OOLD_OPERATING_MODE_SHIFT		(0)

// FW_DXVA_OOLD     FRAME_HEIGHT_MBS
#define FW_DXVA_OOLD_FRAME_HEIGHT_MBS_ALIGNMENT		(2)
#define FW_DXVA_OOLD_FRAME_HEIGHT_MBS_TYPE		IMG_UINT16
#define FW_DXVA_OOLD_FRAME_HEIGHT_MBS_MASK		(0xFFFF)
#define FW_DXVA_OOLD_FRAME_HEIGHT_MBS_LSBMASK		(0xFFFF)
#define FW_DXVA_OOLD_FRAME_HEIGHT_MBS_OFFSET		(0x0010)
#define FW_DXVA_OOLD_FRAME_HEIGHT_MBS_SHIFT		(0)

// FW_DXVA_OOLD     PIC_WIDTH_MBS
#define FW_DXVA_OOLD_PIC_WIDTH_MBS_ALIGNMENT		(2)
#define FW_DXVA_OOLD_PIC_WIDTH_MBS_TYPE		IMG_UINT16
#define FW_DXVA_OOLD_PIC_WIDTH_MBS_MASK		(0xFFFF)
#define FW_DXVA_OOLD_PIC_WIDTH_MBS_LSBMASK		(0xFFFF)
#define FW_DXVA_OOLD_PIC_WIDTH_MBS_OFFSET		(0x0012)
#define FW_DXVA_OOLD_PIC_WIDTH_MBS_SHIFT		(0)

// FW_DXVA_OOLD     SOURCE_LUMA_BUFFER_ADDRESS
#define FW_DXVA_OOLD_SOURCE_LUMA_BUFFER_ADDRESS_ALIGNMENT		(4)
#define FW_DXVA_OOLD_SOURCE_LUMA_BUFFER_ADDRESS_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_SOURCE_LUMA_BUFFER_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_SOURCE_LUMA_BUFFER_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_SOURCE_LUMA_BUFFER_ADDRESS_OFFSET		(0x0014)
#define FW_DXVA_OOLD_SOURCE_LUMA_BUFFER_ADDRESS_SHIFT		(0)

// FW_DXVA_OOLD     SOURCE_CHROMA_BUFFER_ADDRESS
#define FW_DXVA_OOLD_SOURCE_CHROMA_BUFFER_ADDRESS_ALIGNMENT		(4)
#define FW_DXVA_OOLD_SOURCE_CHROMA_BUFFER_ADDRESS_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_SOURCE_CHROMA_BUFFER_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_SOURCE_CHROMA_BUFFER_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_SOURCE_CHROMA_BUFFER_ADDRESS_OFFSET		(0x0018)
#define FW_DXVA_OOLD_SOURCE_CHROMA_BUFFER_ADDRESS_SHIFT		(0)

// FW_DXVA_OOLD     SOURCE_MB_PARAM_ADDRESS
#define FW_DXVA_OOLD_SOURCE_MB_PARAM_ADDRESS_ALIGNMENT		(4)
#define FW_DXVA_OOLD_SOURCE_MB_PARAM_ADDRESS_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_SOURCE_MB_PARAM_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_SOURCE_MB_PARAM_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_SOURCE_MB_PARAM_ADDRESS_OFFSET		(0x001C)
#define FW_DXVA_OOLD_SOURCE_MB_PARAM_ADDRESS_SHIFT		(0)

// FW_DXVA_OOLD     TARGET_LUMA_BUFFER_ADDRESS
#define FW_DXVA_OOLD_TARGET_LUMA_BUFFER_ADDRESS_ALIGNMENT		(4)
#define FW_DXVA_OOLD_TARGET_LUMA_BUFFER_ADDRESS_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_TARGET_LUMA_BUFFER_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_TARGET_LUMA_BUFFER_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_TARGET_LUMA_BUFFER_ADDRESS_OFFSET		(0x0020)
#define FW_DXVA_OOLD_TARGET_LUMA_BUFFER_ADDRESS_SHIFT		(0)

// FW_DXVA_OOLD     TARGET_CHROMA_BUFFER_ADDRESS
#define FW_DXVA_OOLD_TARGET_CHROMA_BUFFER_ADDRESS_ALIGNMENT		(4)
#define FW_DXVA_OOLD_TARGET_CHROMA_BUFFER_ADDRESS_TYPE		IMG_UINT32
#define FW_DXVA_OOLD_TARGET_CHROMA_BUFFER_ADDRESS_MASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_TARGET_CHROMA_BUFFER_ADDRESS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_OOLD_TARGET_CHROMA_BUFFER_ADDRESS_OFFSET		(0x0024)
#define FW_DXVA_OOLD_TARGET_CHROMA_BUFFER_ADDRESS_SHIFT		(0)

#define FW_DXVA_CMD_COMPLETED_SIZE		(12)

// FW_DXVA_CMD_COMPLETED     MSG_SIZE
#define FW_DXVA_CMD_COMPLETED_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_CMD_COMPLETED_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_CMD_COMPLETED_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_CMD_COMPLETED_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_CMD_COMPLETED_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_CMD_COMPLETED_MSG_SIZE_SHIFT		(0)

// FW_DXVA_CMD_COMPLETED     ID
#define FW_DXVA_CMD_COMPLETED_ID_ALIGNMENT		(1)
#define FW_DXVA_CMD_COMPLETED_ID_TYPE		IMG_UINT8
#define FW_DXVA_CMD_COMPLETED_ID_MASK		(0xFF)
#define FW_DXVA_CMD_COMPLETED_ID_LSBMASK		(0xFF)
#define FW_DXVA_CMD_COMPLETED_ID_OFFSET		(0x0001)
#define FW_DXVA_CMD_COMPLETED_ID_SHIFT		(0)

// FW_DXVA_CMD_COMPLETED     FENCE_VALUE
#define FW_DXVA_CMD_COMPLETED_FENCE_VALUE_ALIGNMENT		(4)
#define FW_DXVA_CMD_COMPLETED_FENCE_VALUE_TYPE		IMG_UINT32
#define FW_DXVA_CMD_COMPLETED_FENCE_VALUE_MASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_COMPLETED_FENCE_VALUE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_COMPLETED_FENCE_VALUE_OFFSET		(0x0004)
#define FW_DXVA_CMD_COMPLETED_FENCE_VALUE_SHIFT		(0)

// FW_DXVA_CMD_COMPLETED     FLAGS
#define FW_DXVA_CMD_COMPLETED_FLAGS_ALIGNMENT		(4)
#define FW_DXVA_CMD_COMPLETED_FLAGS_TYPE		IMG_UINT32
#define FW_DXVA_CMD_COMPLETED_FLAGS_MASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_COMPLETED_FLAGS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_COMPLETED_FLAGS_OFFSET		(0x0008)
#define FW_DXVA_CMD_COMPLETED_FLAGS_SHIFT		(0)

#define FW_DXVA_CMD_FAILED_SIZE		(12)

// FW_DXVA_CMD_FAILED     MSG_SIZE
#define FW_DXVA_CMD_FAILED_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_CMD_FAILED_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_CMD_FAILED_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_CMD_FAILED_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_CMD_FAILED_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_CMD_FAILED_MSG_SIZE_SHIFT		(0)

// FW_DXVA_CMD_FAILED     ID
#define FW_DXVA_CMD_FAILED_ID_ALIGNMENT		(1)
#define FW_DXVA_CMD_FAILED_ID_TYPE		IMG_UINT8
#define FW_DXVA_CMD_FAILED_ID_MASK		(0xFF)
#define FW_DXVA_CMD_FAILED_ID_LSBMASK		(0xFF)
#define FW_DXVA_CMD_FAILED_ID_OFFSET		(0x0001)
#define FW_DXVA_CMD_FAILED_ID_SHIFT		(0)

// FW_DXVA_CMD_FAILED     FLAGS
#define FW_DXVA_CMD_FAILED_FLAGS_ALIGNMENT		(2)
#define FW_DXVA_CMD_FAILED_FLAGS_TYPE		IMG_UINT16
#define FW_DXVA_CMD_FAILED_FLAGS_MASK		(0xFFFF)
#define FW_DXVA_CMD_FAILED_FLAGS_LSBMASK		(0xFFFF)
#define FW_DXVA_CMD_FAILED_FLAGS_OFFSET		(0x0002)
#define FW_DXVA_CMD_FAILED_FLAGS_SHIFT		(0)

// FW_DXVA_CMD_FAILED     FENCE_VALUE
#define FW_DXVA_CMD_FAILED_FENCE_VALUE_ALIGNMENT		(4)
#define FW_DXVA_CMD_FAILED_FENCE_VALUE_TYPE		IMG_UINT32
#define FW_DXVA_CMD_FAILED_FENCE_VALUE_MASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_FAILED_FENCE_VALUE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_FAILED_FENCE_VALUE_OFFSET		(0x0004)
#define FW_DXVA_CMD_FAILED_FENCE_VALUE_SHIFT		(0)

// FW_DXVA_CMD_FAILED     IRQSTATUS
#define FW_DXVA_CMD_FAILED_IRQSTATUS_ALIGNMENT		(4)
#define FW_DXVA_CMD_FAILED_IRQSTATUS_TYPE		IMG_UINT32
#define FW_DXVA_CMD_FAILED_IRQSTATUS_MASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_FAILED_IRQSTATUS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_CMD_FAILED_IRQSTATUS_OFFSET		(0x0008)
#define FW_DXVA_CMD_FAILED_IRQSTATUS_SHIFT		(0)

#define FW_DXVA_DEBLOCK_REQUIRED_SIZE		(8)

// FW_DXVA_DEBLOCK_REQUIRED     MSG_SIZE
#define FW_DXVA_DEBLOCK_REQUIRED_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_DEBLOCK_REQUIRED_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_DEBLOCK_REQUIRED_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_DEBLOCK_REQUIRED_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_DEBLOCK_REQUIRED_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_DEBLOCK_REQUIRED_MSG_SIZE_SHIFT		(0)

// FW_DXVA_DEBLOCK_REQUIRED     ID
#define FW_DXVA_DEBLOCK_REQUIRED_ID_ALIGNMENT		(1)
#define FW_DXVA_DEBLOCK_REQUIRED_ID_TYPE		IMG_UINT8
#define FW_DXVA_DEBLOCK_REQUIRED_ID_MASK		(0xFF)
#define FW_DXVA_DEBLOCK_REQUIRED_ID_LSBMASK		(0xFF)
#define FW_DXVA_DEBLOCK_REQUIRED_ID_OFFSET		(0x0001)
#define FW_DXVA_DEBLOCK_REQUIRED_ID_SHIFT		(0)

// FW_DXVA_DEBLOCK_REQUIRED     CONTEXT
#define FW_DXVA_DEBLOCK_REQUIRED_CONTEXT_ALIGNMENT		(4)
#define FW_DXVA_DEBLOCK_REQUIRED_CONTEXT_TYPE		IMG_UINT32
#define FW_DXVA_DEBLOCK_REQUIRED_CONTEXT_MASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_REQUIRED_CONTEXT_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_DEBLOCK_REQUIRED_CONTEXT_OFFSET		(0x0004)
#define FW_DXVA_DEBLOCK_REQUIRED_CONTEXT_SHIFT		(0)

#define FW_DXVA_HW_PANIC_SIZE		(12)

// FW_DXVA_HW_PANIC     FLAGS
#define FW_DXVA_HW_PANIC_FLAGS_ALIGNMENT		(2)
#define FW_DXVA_HW_PANIC_FLAGS_TYPE		IMG_UINT16
#define FW_DXVA_HW_PANIC_FLAGS_MASK		(0xFFFF)
#define FW_DXVA_HW_PANIC_FLAGS_LSBMASK		(0xFFFF)
#define FW_DXVA_HW_PANIC_FLAGS_OFFSET		(0x0002)
#define FW_DXVA_HW_PANIC_FLAGS_SHIFT		(0)

// FW_DXVA_HW_PANIC     MSG_SIZE
#define FW_DXVA_HW_PANIC_MSG_SIZE_ALIGNMENT		(1)
#define FW_DXVA_HW_PANIC_MSG_SIZE_TYPE		IMG_UINT8
#define FW_DXVA_HW_PANIC_MSG_SIZE_MASK		(0xFF)
#define FW_DXVA_HW_PANIC_MSG_SIZE_LSBMASK		(0xFF)
#define FW_DXVA_HW_PANIC_MSG_SIZE_OFFSET		(0x0000)
#define FW_DXVA_HW_PANIC_MSG_SIZE_SHIFT		(0)

// FW_DXVA_HW_PANIC     ID
#define FW_DXVA_HW_PANIC_ID_ALIGNMENT		(1)
#define FW_DXVA_HW_PANIC_ID_TYPE		IMG_UINT8
#define FW_DXVA_HW_PANIC_ID_MASK		(0xFF)
#define FW_DXVA_HW_PANIC_ID_LSBMASK		(0xFF)
#define FW_DXVA_HW_PANIC_ID_OFFSET		(0x0001)
#define FW_DXVA_HW_PANIC_ID_SHIFT		(0)

// FW_DXVA_HW_PANIC     FENCE_VALUE
#define FW_DXVA_HW_PANIC_FENCE_VALUE_ALIGNMENT		(4)
#define FW_DXVA_HW_PANIC_FENCE_VALUE_TYPE		IMG_UINT32
#define FW_DXVA_HW_PANIC_FENCE_VALUE_MASK		(0xFFFFFFFF)
#define FW_DXVA_HW_PANIC_FENCE_VALUE_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_HW_PANIC_FENCE_VALUE_OFFSET		(0x0004)
#define FW_DXVA_HW_PANIC_FENCE_VALUE_SHIFT		(0)

// FW_DXVA_HW_PANIC     IRQSTATUS
#define FW_DXVA_HW_PANIC_IRQSTATUS_ALIGNMENT		(4)
#define FW_DXVA_HW_PANIC_IRQSTATUS_TYPE		IMG_UINT32
#define FW_DXVA_HW_PANIC_IRQSTATUS_MASK		(0xFFFFFFFF)
#define FW_DXVA_HW_PANIC_IRQSTATUS_LSBMASK		(0xFFFFFFFF)
#define FW_DXVA_HW_PANIC_IRQSTATUS_OFFSET		(0x0008)
#define FW_DXVA_HW_PANIC_IRQSTATUS_SHIFT		(0)



#ifdef __cplusplus
}
#endif

#endif /* __DXVA_CMDSEQ_MSG_H__ */
